version: "3"

services:
  sales-web:
    build: .
    volumes:
      - .:/var/www/html
    depends_on:
      - sales-db
    container_name: sales-web
    restart: always
    ports:
      - "5000:5000"
    networks:
        sales-network:
            ipv4_address: 11.11.1.1
  sales-db:
    image: "postgres:latest"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "testing"
    volumes:
        - db-data:/var/lib/postgresql/data
    container_name: sales-db
    restart: always
    ports:
        -   "5435:5432"
    networks:
      sales-network:
            ipv4_address: 11.11.1.2
volumes:
    db-data:
        driver: local
networks:
    sales-network:
        ipam:
            driver: default
            config:
                - subnet: 11.11.0.0/16

